explanations = {
    ("Reading and Writing", "Command of Evidence (Textual)", "Misinterpreted Evidence"):
        "Misinterpreted Evidence occurs when you select evidence from a passage that doesn’t directly support the question’s claim, often because you misread the passage or misunderstood the question’s focus. This mistake is common in Command of Evidence questions, where the SAT asks you to identify a specific line that backs up a statement. For example, if the question asks, 'Which choice provides the best evidence for the author’s claim that renewable energy is cost-effective?' and the passage states, 'Solar panels have decreased in cost by 50% over the past decade,' but you choose a line about their environmental benefits instead, you’ve misinterpreted the evidence. This happens when you focus on a related but irrelevant detail or fail to connect the evidence directly to the claim. It’s a frequent error under time pressure, as you might skim too quickly and latch onto familiar keywords without ensuring they align with the question.\n\n"
        "To fix this, start by identifying the main claim in the question—underline it if needed—and then scan the passage for lines that directly support that claim, not just the general topic. In the example above, you should look for a line about cost, not environmental impact. Practice active reading by summarizing each paragraph in your own words to ensure you understand the key points before selecting evidence. When dealing with paired passages, ensure the evidence you choose aligns with the specific passage referenced in the question. Additionally, if the question involves a quote from the passage, reread the surrounding lines to confirm the context matches the claim.\n\n"
        "Let’s consider a practice scenario: A passage discusses a new species of fish, and the question asks, 'Which choice best supports the claim that the fish adapts well to cold water?' The correct evidence is a line stating, 'The fish’s metabolic rate increases in temperatures below 10°C,' but you choose a line about its diet. To avoid this, you’d first identify the claim (adaptation to cold water) and then look for a line about temperature effects, not diet. A good tip is to practice with SAT Reading passages on platforms like Khan Academy, focusing on Command of Evidence questions, and always justify your choice by connecting it back to the claim. You can also try annotating passages during practice, marking lines that seem like potential evidence to train your eye for relevant details.\n\n"
        "Finally, build a habit of cross-checking your evidence after selecting it. Ask yourself, 'Does this line directly prove the claim, or am I assuming a connection?' If you’re unsure, reread the question and the evidence together to ensure they align. Over time, this will train you to be more precise. If you consistently struggle with this mistake type, review past SAT tests to identify patterns in the types of evidence the SAT prioritizes (e.g., direct quotes over general statements). You might also benefit from working with a study partner to discuss your evidence choices, as explaining your reasoning can help clarify your thought process. This targeted practice will help you improve your evidence selection skills and boost your Reading and Writing score.",

    ("Reading and Writing", "Command of Evidence (Quantitative)", "Misinterpreted Evidence"):
        "Misinterpreted Evidence in quantitative contexts happens when you misread or misinterpret a graph, table, or data set, selecting data that doesn’t align with the question’s claim. This is common in Command of Evidence (Quantitative) questions, where the SAT asks you to use data to support a statement. For example, a table might show a city’s energy usage, with solar energy at 20% in 2022 and 30% in 2023, and the question asks, 'Which data best supports the claim that solar energy use is increasing?' If you choose a data point about wind energy instead, you’ve misinterpreted the evidence by focusing on the wrong category. This error often occurs when you misread labels, confuse data points, or fail to connect the data to the specific claim, especially under time pressure.\n\n"
        "To correct this, carefully examine the data set before answering: check the labels, units, and trends (e.g., increasing or decreasing). In the example, you’d confirm that solar energy increased from 20% to 30%, directly supporting the claim, and ignore irrelevant data like wind energy. Practice this by working on SAT-style data interpretation questions, writing down the key data points (e.g., 'Solar: 2022 = 20%, 2023 = 30%') before selecting an answer. If the data involves percentages or ratios, ensure you understand what they represent—e.g., is it a percentage of total energy or a specific sector? Also, pay attention to the question’s wording: if it asks for a trend, look for changes over time; if it asks for a comparison, focus on differences between categories.\n\n"
        "Here’s a practice scenario: A graph shows a company’s profits over three years—2021: $1M, 2022: $1.2M, 2023: $1.1M—and the question asks, 'Which data best supports the claim that profits peaked in 2022?' If you choose the 2023 data point ($1.1M), you’ve misinterpreted the evidence. Instead, you’d identify 2022’s $1.2M as the highest, supporting the claim. A tip is to practice with SAT Math and Reading questions involving data, focusing on extracting relevant information. You can also use online tools like Desmos to visualize data trends during practice, helping you get comfortable with interpreting graphs and tables.\n\n"
        "To prevent this mistake long-term, always write down the data points you’re using before answering, and verify them against the chart. If you struggle with specific data types (e.g., line graphs vs. bar charts), focus practice on those formats using resources like the College Board’s official SAT practice tests. Additionally, time yourself during practice to simulate test conditions, as rushing often leads to misinterpretation. Over time, this will improve your data analysis skills, ensuring you select the right evidence and answer quantitative Command of Evidence questions correctly.",

    ("Reading and Writing", "Inferences", "Incorrect Inference"):
        "Incorrect Inference occurs when you draw a conclusion not supported by the passage, often by overgeneralizing, misinterpreting tone, or making assumptions beyond the text. This mistake is common in Inference questions, where the SAT tests your ability to understand implicit information. For example, a passage might state, 'The researcher noted a 10% increase in bird migration after a new park opened,' and the question asks, 'What can be inferred about the park’s impact?' If you infer, 'The park caused the increase in migration,' you’ve made an Incorrect Inference—the passage only notes a correlation, not causation. This error happens when you go beyond the text’s evidence, often due to preconceived ideas or misreading subtle cues like tone or qualifiers (e.g., 'noted' vs. 'caused').\n\n"
        "To fix this, focus on sticking to what the text explicitly suggests, and avoid assumptions. In the example, the passage shows a correlation (migration increased after the park opened), so a safer inference is, 'The park may have contributed to the increase in migration.' Practice this by reading SAT passages and writing down the evidence for each inference you make, ensuring it’s directly supported by the text. Pay attention to qualifiers like 'may,' 'suggests,' or 'likely,' which indicate uncertainty, and avoid absolute conclusions unless the passage is definitive. If the passage includes a tone (e.g., skeptical, optimistic), ensure your inference matches it—e.g., a skeptical tone might not support a positive inference.\n\n"
        "Consider this scenario: A passage says, 'The city’s new policy reduced traffic by 15%, though some residents complained about longer commutes.' The question asks, 'What can be inferred about resident satisfaction?' If you infer, 'Residents were unhappy with the policy,' you’ve overgeneralized—only 'some' residents complained, so a better inference is, 'Some residents may be dissatisfied due to longer commutes.' A tip is to practice with SAT Reading passages, focusing on Inference questions, and always list the evidence supporting your conclusion. You can also read short articles (e.g., from BBC News) and practice making inferences, checking if they’re supported by the text.\n\n"
        "To prevent this mistake in the future, after making an inference, ask yourself, 'Does the passage explicitly or implicitly support this, or am I adding my own ideas?' If you’re unsure, err on the side of a more conservative inference. If you frequently make this error, review past SAT tests to see how the correct answers balance evidence and conclusion, and practice with a timer to get used to making quick, accurate inferences. Over time, this will help you develop a more disciplined approach to Inference questions, improving your Reading and Writing score.",

    ("Reading and Writing", "Words in Context", "Vocabulary Misunderstanding"):
        "Vocabulary Misunderstanding happens when you select the wrong meaning of a word in a Words in Context question, often because you’re unfamiliar with the word or ignore the surrounding context. The digital SAT frequently uses words with multiple meanings, testing your ability to infer the correct definition based on the passage. For instance, if a passage says, 'The scientist’s theory was a novel approach to climate modeling,' and the question asks for the meaning of 'novel,' the correct answer is 'new,' but you might choose 'fictional' (as in a novel book) if you don’t consider the context. This mistake stems from relying on the most common definition of a word rather than the passage’s clues, or from a limited vocabulary that makes you second-guess the intended meaning.\n\n"
        "To correct this, focus on the sentence containing the word and the sentences around it to determine its meaning. Look for context clues like synonyms, antonyms, or the overall tone of the passage. In the example above, 'approach to climate modeling' suggests a method or idea, and the positive tone implies innovation, pointing to 'new' rather than 'fictional.' Practice this skill by reading short passages and underlining context clues that hint at a word’s meaning, even for words you think you know. If you’re unfamiliar with a word, eliminate clearly wrong answers first, then use context to narrow down the options. Over time, you’ll get better at spotting how the SAT uses familiar words in unfamiliar ways.\n\n"
        "Here’s a practice example: A passage states, 'The mayor’s decision to veto the bill was a grave mistake,' and the question asks for the meaning of 'grave.' The options are 'serious,' 'buried,' 'engraved,' and 'calm.' If you pick 'buried' (thinking of a graveyard), you’ve misunderstood the context. Instead, note that 'mistake' suggests a negative outcome, and 'veto the bill' is a serious action, so 'grave' means 'serious.' A helpful tip is to build your vocabulary with SAT-specific word lists (available on sites like Quizlet) and practice Words in Context questions, aiming to identify at least three context clues per question. You can also keep a vocabulary journal, noting new words and their meanings in different contexts.\n\n"
        "To prevent this mistake in the future, always substitute your chosen definition back into the sentence to see if it makes sense. For 'grave mistake,' 'serious mistake' fits, but 'buried mistake' doesn’t. If you find vocabulary consistently challenging, dedicate 10 minutes daily to learning 5 new SAT words, focusing on their multiple meanings, and read diverse texts (e.g., scientific articles, editorials) to see words in context. Additionally, practice with a timer to simulate test conditions, as time pressure can lead to rushed guesses. This combination of context practice and vocabulary building will help you tackle Words in Context questions more effectively.",

    ("Reading and Writing", "Central Ideas and Details", "Missed Key Detail"):
        "Missed Key Detail occurs when you overlook a critical piece of information in the passage, leading to an incorrect answer in Central Ideas and Details questions. These questions test your ability to identify the main idea or a specific detail that supports it, but missing a key detail can throw off your understanding. For example, a passage might discuss a new recycling program, stating, 'The program increased recycling rates by 30% in its first year, though participation dropped in rural areas.' If the question asks, 'What is the main outcome of the program?' and you answer 'It failed in rural areas,' you’ve missed the key detail—the 30% increase in recycling rates, which is the primary outcome. This mistake often happens when you focus on a secondary detail, skim too quickly, or fail to prioritize the passage’s main focus.\n\n"
        "To address this, practice active reading by pausing after each paragraph to summarize its main point in your own words. In the example, you’d note that the paragraph’s focus is the program’s success (30% increase), with the rural drop as a secondary detail. When answering, always refer back to the passage to confirm the detail you’re basing your answer on, especially for questions asking about outcomes or main ideas. Look for numbers, percentages, or strong adjectives (like 'significant' or 'major') that often signal key details in SAT passages. If you’re unsure, reread the first and last sentences of the paragraph, as they often contain the main idea or a summary of key points.\n\n"
        "Consider this scenario: A passage about a new species of bird says, 'The bird’s bright feathers attract mates, but its small size makes it vulnerable to predators.' The question asks, 'What is the primary characteristic of the bird mentioned in the passage?' If you choose 'small size,' you’ve missed the key detail—the passage emphasizes the bright feathers as the primary trait, with size as a secondary note. To avoid this, you’d summarize the passage as 'The bird is notable for its bright feathers, which help with mating, despite its small size,' ensuring you prioritize the main detail. A tip is to practice with SAT Reading passages, focusing on identifying the main idea of each paragraph before answering questions. You can also try highlighting key details during practice to train your eye for what matters most.\n\n"
        "To build this skill long-term, work on your skimming and scanning techniques. Skim for structure (e.g., topic sentences) and scan for specific details (e.g., numbers, examples) when answering questions. If you frequently miss details, try reading passages twice—once quickly to get the gist, and once more carefully to note key points. You might also benefit from discussing passages with a study group, as explaining the main idea to others can reinforce your understanding. Over time, this will help you retain critical information and improve your accuracy on Central Ideas and Details questions.",

    ("Reading and Writing", "Boundaries", "Grammatical Error"):
        "Grammatical Error mistakes happen when you fail to apply a grammar rule correctly in Standard English Conventions questions, such as those testing sentence structure in Boundaries. For instance, in a question asking you to correct a sentence like, 'The team of researchers, who studies climate change, are meeting tomorrow,' you might miss that 'are' should be 'is' because the subject 'team' is singular, not plural. This error, a subject-verb agreement issue, often occurs when you’re distracted by a modifying phrase ('who studies climate change') or rush through the question without analyzing the sentence’s core structure. It’s a common mistake when you’re not familiar with grammar rules or don’t take the time to break down the sentence.\n\n"
        "To fix this, break down the sentence to its basic components: identify the subject and verb, and ensure they agree in number and tense. In the example, the subject is 'team' (singular), so the verb should be 'is,' not 'are.' Ignore distracting phrases by mentally simplifying the sentence—'The team is meeting tomorrow'—to check agreement. Practice this by rewriting complex sentences in their simplest form during practice sessions, focusing on common SAT grammar rules like subject-verb agreement, pronoun agreement, and verb tense consistency. If the question involves punctuation (e.g., fixing a run-on sentence), ensure you understand how to use commas, semicolons, or periods to separate clauses correctly.\n\n"
        "Here’s another example: A sentence reads, 'Each of the students have submitted their project,' and you need to correct it. If you leave it as is, you’ve made a grammatical error—'have' should be 'has' because 'each' is singular, and 'their' should be 'his or her' for agreement (though the SAT often accepts 'their' in modern usage). To catch this, isolate the subject ('each') and verb ('have'), and correct to 'has.' A useful tip is to practice with SAT Writing questions on Khan Academy, focusing on Standard English Conventions, and keep a grammar cheat sheet handy for rules like agreement, tense, and punctuation. You can also use grammar apps like Grammarly to identify patterns in your errors during practice.\n\n"
        "To prevent grammatical errors long-term, review one grammar rule per day (e.g., subject-verb agreement on Monday, pronoun agreement on Tuesday) and apply it to 5 practice sentences. If you struggle with specific rules, track your errors in a notebook to identify patterns, and focus practice on those areas. Additionally, read well-written texts (e.g., editorials in The New York Times) to internalize proper grammar and sentence structure. Over time, this targeted practice will make grammar rules second nature, reducing errors in Boundaries questions and boosting your Reading and Writing score.",

    ("Reading and Writing", "Form/Structure/Sense", "Grammatical Error"):
        "Grammatical Errors in Form/Structure/Sense questions occur when you misuse verb tense, subject-verb agreement, or pronoun reference, often because you overlook the sentence’s structure or context. For example, a sentence might read, 'The committee, which meet every month, have decided to approve the plan,' and the question asks you to correct it. If you miss that 'have' should be 'has' (since 'committee' is singular) and 'meet' should be 'meets' (for tense consistency), you’ve made a Grammatical Error. This mistake happens when you don’t analyze the sentence’s subject-verb pairs or fail to ensure consistency across the sentence, often due to time pressure or unfamiliarity with grammar rules.\n\n"
        "To correct this, identify the subject and verb in each clause, ensuring they agree in number and tense. In the example, the subject 'committee' is singular, so the verbs should be 'meets' and 'has.' Check for consistency: if the sentence uses present tense ('meets'), the decision should also be present ('has decided'). Practice this by breaking down SAT Writing sentences into their core components, ignoring modifiers, and verifying agreement and tense. If the question involves pronouns, ensure they match their antecedents in number and gender—e.g., 'the committee' should use 'it,' not 'they,' unless the context specifies otherwise.\n\n"
        "Here’s a practice example: A sentence states, 'The group of volunteers, who was trained last week, are now leading the project.' The errors are 'was' (should be 'were' because 'volunteers' is plural) and 'are' (should be 'is' because 'group' is singular). To fix this, you’d correct to 'The group of volunteers, who were trained last week, is now leading the project.' A tip is to practice with SAT Writing questions focusing on Form/Structure/Sense, and create a grammar checklist (e.g., check subject-verb agreement, tense consistency, pronoun reference) to use during practice. You can also review grammar rules using resources like The Elements of Style by Strunk and White.\n\n"
        "To prevent this mistake in the future, practice rewriting sentences with correct grammar, focusing on one rule at a time (e.g., verb tense consistency). If you frequently make these errors, work with a tutor or study group to get feedback on your corrections, as discussing your mistakes can help clarify rules. Additionally, time yourself during practice to build speed without sacrificing accuracy, as rushing often leads to grammatical oversights. Over time, this will help you internalize grammar rules, improving your performance on Form/Structure/Sense questions.",

    ("Reading and Writing", "Transitions", "Logical Disconnect"):
        "Logical Disconnect occurs when you choose a transition that doesn’t fit the passage’s logical flow in Transitions questions, breaking the coherence between ideas. The digital SAT tests your ability to connect ideas smoothly, so picking the wrong transition word—like using 'however' when 'therefore' is needed—can confuse the reader. For example, a passage might say, 'The city invested in public transit. Ridership increased by 20%.' If the question asks for the best transition between these sentences, and you choose 'however' (implying contrast), you’ve created a logical disconnect because the second sentence supports the first, requiring a word like 'as a result.' This mistake often happens when you don’t fully grasp the relationship between the ideas or misinterpret the passage’s tone.\n\n"
        "To fix this, identify the relationship between the two ideas before selecting a transition: are they cause-and-effect, contrast, addition, or sequence? In the example, 'invested in public transit' (cause) leads to 'ridership increased' (effect), so a cause-and-effect transition like 'as a result' or 'therefore' is appropriate. Practice by categorizing common SAT transition words into groups: contrast (however, on the other hand), cause-effect (therefore, as a result), addition (moreover, also), and sequence (then, next). When answering, test your choice by reading the sentences aloud to ensure the flow makes sense. If the passage has a specific tone (e.g., formal), ensure the transition matches that tone—e.g., 'thus' might be better than 'so' in a scientific passage.\n\n"
        "Consider this scenario: A passage states, 'The experiment failed due to contamination. The team redesigned the procedure.' The question asks for the best transition. If you choose 'for example,' you’ve created a logical disconnect—'for example' suggests the second sentence illustrates the first, but it’s actually a response to the failure. The correct transition is 'consequently,' showing cause-and-effect. A tip is to practice with SAT Writing passages, focusing on Transitions questions, and write down the relationship between sentences before choosing an answer. You can also create a transition word bank, noting their meanings and practicing their use in different contexts.\n\n"
        "To prevent this mistake in the future, build a mental checklist: after selecting a transition, ask, 'Does this word match the relationship between the ideas?' If not, try another option. If Logical Disconnect errors persist, review past SAT tests to see how transitions are used in context, and practice rewriting sentences with different transitions to understand their nuances. Additionally, read well-structured essays (e.g., from The Atlantic) to see how transitions create flow, and mimic this in your practice. This will help you improve your logical reasoning and ensure smoother connections in your answers.",

    ("Reading and Writing", "Rhetorical Synthesis", "Logical Disconnect"):
        "Logical Disconnect in Rhetorical Synthesis questions happens when you struggle to combine ideas logically, often because you misinterpret the rhetorical goal or the relationship between the ideas. These questions ask you to synthesize information, such as combining data from a passage and a graph to support a claim, and a wrong choice can break the logical flow. For example, a passage might discuss a school’s new tutoring program, stating, 'Test scores improved by 15%,' and a graph shows that 80% of students attended tutoring. If the question asks for a synthesis statement and you choose, 'Tutoring was unpopular, so scores improved,' you’ve created a logical disconnect—the graph shows high attendance (80%), contradicting 'unpopular.' This error occurs when you misread the data or don’t align your synthesis with the passage’s purpose (e.g., to inform, persuade).\n\n"
        "To correct this, focus on the author’s purpose and the relationship between the ideas you’re synthesizing. In the example, the passage’s purpose is to inform about the program’s success, and the graph supports this by showing high attendance. A correct synthesis would be, 'The tutoring program’s high attendance (80%) likely contributed to the 15% improvement in test scores.' Practice this by working on SAT Writing questions that involve paired passages or data, ensuring your synthesis aligns with the passage’s goal and the data’s implications. If the question involves a specific rhetorical goal (e.g., to persuade), ensure your answer strengthens that goal—e.g., emphasizing positive outcomes in a persuasive context.\n\n"
        "Here’s a practice scenario: A passage states, 'The city’s new park increased tourism by 10%,' and a table shows visitor numbers: 2022 (before park): 50,000; 2023 (after park): 55,000. The question asks for a synthesis statement. If you choose, 'The park had no impact on tourism, as numbers remained stable,' you’ve created a logical disconnect—the table shows an increase (50,000 to 55,000), matching the 10% rise. A correct synthesis is, 'The new park’s opening led to a 10% increase in tourism, as visitor numbers rose from 50,000 to 55,000.' A tip is to practice with SAT Writing questions involving Rhetorical Synthesis, focusing on combining text and data logically, and always check that your statement reflects both sources accurately.\n\n"
        "To prevent this mistake in the future, after writing your synthesis, ask, 'Does this statement logically connect the passage and data, and does it align with the rhetorical goal?' If not, revise your answer. If you struggle with synthesis, practice with real-world examples—e.g., read a news article and a related chart, then write a sentence combining them. You can also use SAT prep resources like the College Board’s practice tests to work on synthesis questions under timed conditions. Over time, this will help you develop a stronger sense of logical connections, improving your performance on Rhetorical Synthesis questions.",

    ("Reading and Writing", "Text Structure and Purpose", "Style/Clarity Issue"):
        "Style/Clarity Issues arise when you select an answer that is less concise, less precise, or doesn’t match the passage’s tone in Expression of Ideas questions, such as those testing Text Structure and Purpose. The SAT values clear, effective communication, so choosing a wordy or mismatched option can hurt your score. For example, a passage might say, 'The policy was implemented to reduce emissions,' and the question asks for the most precise revision of 'implemented.' If you choose 'put into action in a manner that was effective,' you’ve introduced a Style/Clarity Issue because it’s wordier than 'enacted,' which is more concise and fits the formal tone. This mistake often occurs when you overlook the passage’s style, prioritize complexity over clarity, or don’t consider the audience’s expectations.\n\n"
        "To fix this, always choose the option that is most concise while maintaining the passage’s meaning and tone. In the example, 'enacted' is a single word that means 'implemented' and matches the formal, straightforward tone of a policy discussion, whereas 'put into action in a manner that was effective' is unnecessarily verbose. When practicing, compare answer choices side by side, asking, 'Which option says the same thing in the fewest words without losing meaning?' Pay attention to the passage’s tone—formal, neutral, or conversational—and ensure your choice aligns with it. For instance, in a scientific passage, avoid casual phrases like 'kicked off' for 'initiated.' If the question involves redundancy, eliminate unnecessary words—e.g., 'in order to' can often be shortened to 'to.'\n\n"
        "Here’s a practice example: A passage states, 'The scientist conducted a study to examine the effects of pollution,' and the question asks for the most precise revision of 'conducted a study to examine.' If you choose 'carried out an investigation to look into,' you’ve made a Style/Clarity Issue—'investigated' alone is more concise and equally precise. To avoid this, you’d select 'investigated,' which reduces wordiness while preserving meaning. A tip is to read high-quality writing (e.g., articles from The New York Times) to internalize clear, concise styles, and practice SAT Writing questions focusing on Expression of Ideas. You can also rewrite sentences in your own words during practice, aiming for brevity and clarity.\n\n"
        "To prevent this mistake in the future, after selecting an answer, ask, 'Is there a shorter way to say this without losing meaning or changing the tone?' If yes, revise your choice. If you struggle with tone, analyze SAT passages to note their style (e.g., formal in science passages, conversational in narratives) and mimic it in your answers. Additionally, practice with a timer to get used to making quick, clear choices under pressure. Over time, this will help you develop a knack for choosing clear, stylistically appropriate options, improving your performance on Text Structure and Purpose questions.",

    ("Math", "Algebra", "Calculation Error"):
        "Calculation Errors occur when you make a simple arithmetic mistake during a Math problem, such as adding, subtracting, or multiplying incorrectly, leading to a wrong answer despite understanding the concept. This is common in Algebra questions where multiple steps are involved. For example, in solving the equation \(2x + 3 = 11\), you correctly isolate the variable by subtracting 3 from both sides (\(2x = 8\)), but then mistakenly divide 8 by 4 instead of 2, getting \(x = 2\) instead of the correct \(x = 4\). This error often happens when you rush through calculations, misread numbers, or don’t double-check your work, especially under the time pressure of the SAT.\n\n"
        "To address this, slow down during calculations and write out each step clearly, even for simple operations. In the example, after \(2x = 8\), you’d write \(x = 8 \div 2\), then compute \(8 \div 2 = 4\), ensuring accuracy. Always double-check your arithmetic by substituting your answer back into the original equation: for \(x = 4\), \(2(4) + 3 = 11\), which is correct, but for \(x = 2\), \(2(2) + 3 = 7\), which isn’t. Practice this habit by solving 5-10 SAT Math problems daily, focusing on writing out each step and verifying your answer before moving on. If you’re prone to specific errors (e.g., mixing up addition and multiplication), focus practice on those operations.\n\n"
        "Consider this scenario: A question asks for the area of a rectangle with length 6 and width 4, so you compute \(6 \times 4\). If you accidentally calculate \(6 + 4 = 10\) instead of \(6 \times 4 = 24\), you’ve made a Calculation Error. To catch this, you’d recheck your operation—area requires multiplication, not addition—and correct it to 24. A tip is to practice basic arithmetic drills (e.g., multiplication tables, quick addition/subtraction) for 5 minutes daily to build speed and accuracy, reducing these errors over time. You can also use the SAT’s digital calculator for complex computations, but always verify simple ones manually.\n\n"
        "To prevent Calculation Errors in the future, build a habit of checking your work by performing the inverse operation—e.g., if you divided, multiply back to confirm. If you frequently make these mistakes, keep a log of your errors to identify patterns (e.g., always misreading 6 as 8), and practice those specific operations. Additionally, practice under timed conditions to get used to maintaining accuracy under pressure, using resources like the College Board’s SAT practice tests. Over time, this careful approach will minimize arithmetic mistakes, ensuring your conceptual understanding translates to correct answers on Math questions.",

    ("Math", "Advanced Math", "Conceptual Error"):
        "Conceptual Errors happen when you misunderstand a fundamental math concept, leading to an incorrect approach in Advanced Math questions, such as those involving quadratics or exponents. For instance, in solving the quadratic equation \(x^2 - 4x + 4 = 0\), you might mistakenly think it’s a linear equation and solve as \(x^2 - 4x = 0\), factoring to \(x(x - 4) = 0\) and getting \(x = 0\) or \(x = 4\). The correct solution is \((x - 2)^2 = 0\), so \(x = 2\), showing you misunderstood how to handle a perfect square trinomial. This error occurs when you have gaps in foundational knowledge, confuse related concepts, or don’t recognize the problem type.\n\n"
        "To fix this, revisit the specific concept you misunderstood—in this case, quadratic equations. Study the standard form \(ax^2 + bx + c = 0\) and methods to solve it: factoring, quadratic formula, or completing the square. For \(x^2 - 4x + 4 = 0\), recognize the pattern \((x - 2)^2\), or use the quadratic formula: \(x = [-b \pm \sqrt{b^2 - 4ac}]/(2a)\), where \(a = 1\), \(b = -4\), \(c = 4\), so \(x = [4 \pm \sqrt{16 - 16}]/2 = 4/2 = 2\). Practice this by solving 5-10 quadratic equations, trying different methods each time to build familiarity. If the concept involves exponents (e.g., \(x^a \times x^b = x^{a+b}\)), review the rules and apply them to practice problems.\n\n"
        "Here’s another example: A question asks you to simplify \(2^3 \times 2^5\). If you add the exponents instead of multiplying the bases first, thinking \(2^3 \times 2^5 = 2^{15}\), you’ve made a Conceptual Error. The correct approach is \(2^3 \times 2^5 = 2^{3+5} = 2^8 = 256\). To avoid this, review exponent rules and practice with similar problems. A tip is to use SAT prep books like The College Panda’s SAT Math, which break down Advanced Math concepts, and solve 3-5 problems per concept daily, explaining each step aloud to ensure understanding.\n\n"
        "To prevent Conceptual Errors long-term, create a concept cheat sheet with key formulas and rules (e.g., quadratic formula, exponent laws) and review it before practice sessions. If you struggle with specific topics, watch Khan Academy videos on those concepts and follow up with practice problems. You can also work with a study partner to discuss your solutions, as explaining your reasoning can help solidify your understanding. Over time, this targeted practice will help you master Advanced Math concepts, reducing errors and improving your SAT Math score.",

    ("Math", "Algebra", "Setup Error"):
        "Setup Errors occur when you incorrectly set up a problem, such as using the wrong equation or misinterpreting the relationships in Algebra questions. For example, in an Algebra word problem, 'A store sells apples at $2 each and oranges at $3 each, totaling $15 for 6 pieces of fruit. How many apples were sold?' If you set up the equation as \(2a + 3o = 6\) (using the number of fruits as the cost), you’ve made a Setup Error. The correct setup is \(a + o = 6\) (for the number of fruits) and \(2a + 3o = 15\) (for the cost), solving to find \(a = 3\). This mistake happens when you misinterpret the problem’s relationships, rush to write equations, or confuse the given information.\n\n"
        "To correct this, carefully translate the problem into equations by defining variables and writing down what each piece of information represents. In the example, define \(a\) as the number of apples and \(o\) as the number of oranges. The problem gives two pieces of information: \(a + o = 6\) (total fruits) and \(2a + 3o = 15\) (total cost). Solve these simultaneously: substitute \(o = 6 - a\) into the second equation, getting \(2a + 3(6 - a) = 15\), which simplifies to \(2a + 18 - 3a = 15\), so \(-a = -3\), \(a = 3\). Practice this by solving 5-10 SAT word problems, writing out each step of your setup before solving, and checking that your equations match the problem’s conditions.\n\n"
        "Here’s another example: A question asks, 'A car travels 120 miles in 2 hours. What is its speed in miles per hour?' If you set up the equation as \(120 \times 2 = s\) (thinking speed is distance times time), you’ve made a Setup Error. The correct formula is \(s = \text{distance} / \text{time} = 120 / 2 = 60\) mph. To avoid this, identify the formula needed (speed = distance/time) and plug in the values correctly. A tip is to practice SAT Algebra problems, focusing on writing down the formula or equations before solving, and use a checklist: define variables, write equations, verify they match the problem.\n\n"
        "To prevent Setup Errors in the future, always write down your variables and equations before solving, and double-check that they match the problem’s conditions. If you frequently make this mistake, practice translating word problems into equations, starting with simpler ones and gradually increasing complexity. You can also use visual aids (e.g., drawing a diagram for the apples and oranges problem) to clarify relationships. Over time, this will improve your ability to set up problems correctly, ensuring you solve for the right variable and get the correct answer on SAT Math questions.",

    ("Math", "Linear Equations", "Misread Problem"):
        "Misread Problem errors happen when you misunderstand what a Math question is asking, leading you to solve for the wrong variable or answer in the wrong format, often in Linear Equations questions. For example, a question might ask, 'What is the value of \(x\) in the equation \(3x + 5 = 20\) if \(y = 2x\)?' If you solve for \(y\) instead of \(x\), getting \(y = 10\) (since \(x = 5\), so \(y = 2 \times 5\)), you’ve misread the problem—the question only wants \(x = 5\). This error occurs when you don’t carefully read the final ask, get distracted by extra information, or misinterpret the question’s phrasing under time pressure.\n\n"
        "To fix this, underline the specific question being asked before solving, and refer back to it after finding your answer. In the example, the question asks for \(x\), so you’d solve \(3x + 5 = 20\) as \(3x = 15\), \(x = 5\), and stop there, ignoring \(y = 2x\) since it’s not needed. Practice this by working on 5-10 SAT Math problems, underlining the question (e.g., 'What is \(x\)?') and double-checking that your answer matches the request. If the problem asks for a specific format (e.g., a fraction), ensure your answer complies before submitting. Pay attention to keywords like 'value of,' 'total,' or 'difference,' which indicate what you’re solving for.\n\n"
        "Here’s another example: A question states, 'A line has a slope of 2 and passes through the point (1, 3). What is the y-intercept?' If you solve for the slope instead, thinking the question asks for it, you’ve misread the problem—the slope is given (2), and you need the y-intercept. Using the point-slope form \(y - y_1 = m(x - x_1)\), you’d write \(y - 3 = 2(x - 1)\), simplify to \(y = 2x + 1\), and find the y-intercept is 1. A tip is to practice SAT Math questions with word problems, focusing on identifying the final ask before starting your calculations, and write down what you’re solving for (e.g., 'y-intercept').\n\n"
        "To prevent this mistake in the future, build a habit of reading the question twice—once before solving and once after—to confirm you’ve answered correctly. If you often misread problems, practice with SAT Math sections under timed conditions to get used to the phrasing and pressure, using resources like the College Board’s practice tests. You can also summarize the question in your own words (e.g., 'Find the y-intercept') to ensure clarity. Over time, this will help you focus on the question’s goal, reducing errors and improving your accuracy on Linear Equations questions.",

    ("Math", "Problem-Solving and Data Analysis", "Data Misinterpretation"):
        "Data Misinterpretation occurs when you misread or misunderstand a chart, table, or graph in Problem-Solving and Data Analysis questions, leading to an incorrect answer. The digital SAT frequently includes questions with data sets, testing your ability to extract and analyze information accurately. For example, a table might show a company’s sales in 2022 and 2023, with 2022 sales at $500,000 and 2023 sales at $600,000, and the question asks for the percent increase. If you calculate the percent decrease instead, thinking 2023 sales dropped to $500,000, you’ve misinterpreted the data—sales increased from $500,000 to $600,000, so the percent increase is \((600,000 - 500,000) / 500,000 \times 100 = 20\%\). This error often happens when you misread labels, confuse rows/columns, or rush through the data.\n\n"
        "To address this, carefully examine the data set before calculating, noting the labels, units, and trends (e.g., increasing or decreasing). In the example, you’d confirm that 2022 sales are $500,000 and 2023 sales are $600,000, an increase, so you’d use the percent increase formula: \(\text{(new - old)} / \text{old} \times 100\). Practice this by working on 5-10 SAT data interpretation questions, writing down the key data points (e.g., '2022: $500,000, 2023: $600,000') before solving. Double-check your interpretation by ensuring the trend (increase or decrease) matches the question’s ask. If the data involves multiple categories, ensure you’re focusing on the right one—e.g., if the question asks about sales, ignore unrelated data like expenses.\n\n"
        "Consider this scenario: A graph shows a student’s test scores over 4 weeks—Week 1: 70, Week 2: 80, Week 3: 75, Week 4: 85—and the question asks for the week with the largest score increase. If you misread Week 3 as 85 (confusing it with Week 4) and calculate the increase from Week 2 to Week 3 as \(85 - 80 = 5\), you’ve misinterpreted the data. The correct increase is Week 3 to Week 4: \(85 - 75 = 10\). To avoid this, you’d list the scores (70, 80, 75, 85) and calculate each increase: \(80 - 70 = 10\), \(75 - 80 = -5\), \(85 - 75 = 10\), confirming the largest is 10. A tip is to practice with SAT Math questions involving graphs and tables, focusing on extracting data accurately, and use online tools like Desmos to visualize trends during practice.\n\n"
        "To prevent Data Misinterpretation in the future, always write down the data points you’re using before calculating, and verify them against the chart. If you struggle with specific data types (e.g., line graphs vs. bar charts), focus practice on those formats using resources like the College Board’s official SAT practice tests. You can also practice with real-world data sets (e.g., from news articles) to get comfortable interpreting different formats. Over time, this will improve your data analysis skills, ensuring you extract the right information and answer Problem-Solving questions correctly."
}

def get_explanation(section, topic, mistake_type):
    key = (section, topic, mistake_type)
    return explanations.get(key, f"No explanation available for {section} - {topic} - {mistake_type}.")